### ISSUE TITLE
Mapview map might not be displayed on some browsers

### ISSUE THREAD

**Issue by andGarc** [SESYNC-ci/vector-analysis-syracuse-lesson#4]
Mapview results display a  blank page on Safari @ localhost. (Might only be a local issue).

**Comment by qdread** [comment]
This appears to be a problem on other browsers as well (firefox) and is a problem whether the lesson is viewed in the RStudio viewer pane or on GitHub pages in the browser.

So far I have tried out a number of things to fix it, none of which have worked. 

- Solution in https://github.com/r-spatial/mapview/issues/351 didn't work
- Solution in https://github.com/r-spatial/mapview/issues/312 didn't work
- Rolling mapview back to an older version didn't work. I tried several versions going back to 2.3.0 (the version that was current in 2018 when the lesson was developed).
- Updating mapview to a dev version from GitHub didn't even work.

The fact that our GDAL is old as f__k may be part of the problem. When Umiacs finally updates things, that may help.

**Comment by qdread** [comment]
I submitted an issue to mapview: https://github.com/r-spatial/mapview/issues/370

**Comment by qdread** [comment]
Still working on this. For a while I thought it was solved by rolling back leaflet. But ultimately that did not work. I am trying to debug it with different attempts to mess with htmlwidgets. I made a test repo for easier debugging so I do not have to keep building the whole vector lesson: github.com/SESYNC-ci/test-mapview-lesson

**Comment by qdread** [comment]
Fixed by following the procedure in [hotfix.sh](https://github.com/SESYNC-ci/vector-analysis-syracuse-lesson/blob/master/hotfix.sh): 

1. first clean up the repo locally by deleting these four directories: `docs/_site`, `docs/_slides`, `docs/assets/htmlwidgets`, and `cache`.
2. run "Build All"
3. move `leaflet-providers_1.9.0.js` from its location in a subdirectory of `docs/assets/NA` to `docs/assets/htmlwidgets` (previously I also moved a stylesheet called `popup.css` but after the repo cleaning, this stylesheet no longer exists)
4. delete `docs/assets/NA`
5. edit `docs/_data/htmlwidgets.yml` so that the file path for leaflet-providers_1.9.0.js is changed from `src: .na.character` to `src: htmlwidgets`

That's it! All of this can be done point and click, or you can run the relevant lines from hotfix.sh at the appropriate times.

This is a temporary fix and hopefully we can come up with a better permanent solution.
